# 1.ubuntu
pysc:
        # 1-1.イメージの指定
        image: kino002/ubuntu-scraping

        # 1-2.リンク指定
        links:
                - "dbserver:mysql"
        
        # 1-3.起動中にする
        tty: true 
                

# 2.DBサーバの指定
dbserver:
        # 2-1.イメージの指定
        image: mariadb

        # 2-2.環境変数の指定
        environment:
                MYSQL_ROOT_PASSWORD: skip0518

        # 2-3.保存先
        volumes_from:
                - databox

